version: 0.2

phases:

  install:
    runtime-versions:
      golang: 1.18


    commands:

    # Use go modules rather than GOPATH
    - export GO111MODULE="on"
    # Install Testify to use common assertions and mocks in tests
    - go get -u github.com/stretchr/testify
    - go install honnef.co/go/tools/cmd/staticcheck@latest
  pre_build:
    commands:

    # Fetch all dependencies
    - go mod tidy

    # Check for common Go application problems with 'go vet' and staticcheck
    - go vet ./...
    - staticcheck ./...
    # Run all tests included with our application
    - go test ./...

  build:
    commands:

    # Build our go application
    - go build -o main cmd/http/lambda/*.go

    # Copy static assets to S3, and package application with AWS CloudFormation/SAM
    - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

  post_build:
    commands:
    # Do not remove this statement. This command is required for AWS CodeStar projects.
    # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.
    - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json

artifacts:
  files:
  - template-export.yml
  - template-configuration.json
